/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrame.java
 *
 * Created on Feb 25, 2010, 3:58:39 PM
 */
package net.homeip.dvdstore.frame;

import net.homeip.dvdstore.ApplicationContextUtil;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import net.homeip.dvdstore.listener.LoginListener;
import net.homeip.dvdstore.listener.ResultRetrievedListener;
import net.homeip.dvdstore.listener.event.LoginEvent;
import net.homeip.dvdstore.listener.event.ResultRetrievedEvent;
import net.homeip.dvdstore.model.LoginModel;

/**
 *
 * @author VU VIET PHUONG
 */
public class LoginFrame extends javax.swing.JFrame
        implements ResultRetrievedListener {

    private LoginModel loginModel;
    private LoginListener loginListener;

    private void setEnableLogin(boolean enable) {
        btnDangNhap.setEnabled(enable);
    }

    private void dispatchLoginEvent() {
        if (loginListener == null) {
            throw new IllegalStateException("loginListener is null");
        }
        LoginEvent loginEvent = new LoginEvent(this);
        loginEvent.setUserName(txtTenDangNhap.getText());
        loginEvent.setPassword(new String(txtMatKhau.getPassword()));
        loginEvent.setLoginModel(loginModel);
        loginListener.loginPerformed(loginEvent);
    }

    public void onResultRetrieved(ResultRetrievedEvent evt) {
        String msg;
        switch (loginModel.getStatus()) {
            case LoginModel.OK:
                loggedIn();
                return;
            case LoginModel.LOGIN_FAIL:
                msg = "Sai tên đăng nhập hoặc mật khẩu";
                break;
            case LoginModel.SERVER_CONNECTION_ERROR:
                msg = "Không kết nối được với Server";
                break;
            default:
                msg = "Lỗi Server";                
        }
        setEnableLogin(true);
        JOptionPane.showMessageDialog(this, msg);
    }

    private void loggedIn() {
        dispose();
        MainFrame mainFrame = new MainFrame(txtTenDangNhap.getText());
        mainFrame.setVisible(true);
    }

    /** Creates new form LoginFrame */
    public LoginFrame() {
        addLoginListener(((LoginListener)ApplicationContextUtil.
                getApplicationContext().getBean("loginListener")));
        loginModel = new LoginModel();
        loginModel.addResultRetrievedListener(this);
        initComponents();
    }

    public void addLoginListener(LoginListener loginListener) {
        if (loginListener == null) {
            throw new IllegalArgumentException("can't add null loginListener");
        }
        this.loginListener = loginListener;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel loginPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        txtTenDangNhap = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DVDStore");
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Tên đăng nhập: ");
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Mật khẩu: ");
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setText("...............................................");
        loginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, -1));

        jLabel4.setText("...................................");
        loginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, -1));

        txtMatKhau.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginPanel.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 190, -1));

        txtTenDangNhap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        //txtTenDangNhap.addKeyListener(new AlphabetOnlyListener());
        loginPanel.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 190, -1));

        btnDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nav-prefs.png"))); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setBorderPainted(false);
        btnDangNhap.setContentAreaFilled(false);
        btnDangNhap.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/note_edit.png"))); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setBorderPainted(false);
        btnNhapLai.setContentAreaFilled(false);
        btnNhapLai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nav-stop.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setBorderPainted(false);
        btnThoat.setContentAreaFilled(false);
        btnThoat.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(155, 155, 155))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangNhap)
                    .addComponent(btnNhapLai)
                    .addComponent(btnThoat))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-318)/2, 400, 318);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        txtTenDangNhap.setText("");
        txtMatKhau.setText("");
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        setEnableLogin(false);
        dispatchLoginEvent();
    }//GEN-LAST:event_btnDangNhapActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnThoat;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
